package utility;

public enum ApplicationScreen {
    PATHFINDING,
    ADMIN_ADD_NODE,
    ADMIN_EDIT_NODE,
    ADMIN_ADD_EDGE,
    ADMIN_DEL_EDGE,
    ADMIN_MENU,
    ADMIN_INTERPRETER,
    ADMIN_VIEWREQUEST,
    REQUEST_INTERFACE
}
